# Generated by Django 5.1.3 on 2024-12-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('anime_id_mal', models.CharField(default='ZXCV', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name="Anime's MyAnimeList ID")),
                ('roman_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Romanized Title')),
                ('jp_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Japanese Title')),
                ('broadcast_type', models.CharField(choices=[('TV', 'TV Series'), ('MV', 'Movie'), ('ONA', 'ONA'), ('OVA', 'OVA'), ('SP', 'Special')], max_length=10, null=True, verbose_name='Broadcasting Type')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id_spotify', models.CharField(default='ASDF', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name="Artist's Spotify ID")),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Artist Name')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id_spotify', models.CharField(default='QWER', max_length=50, primary_key=True, serialize=False, unique=True, verbose_name="Song's Spotify ID")),
                ('song_name_roman', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Romanized Song Name')),
                ('song_name_jp', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Japanese Song Name')),
                ('song_type', models.CharField(choices=[('O', 'Opening'), ('E', 'Ending'), ('I', 'Insert')], db_index=True, max_length=10, null=True, verbose_name='Song Type')),
                ('anime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='search_engine.anime', verbose_name='Related Anime')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='search_engine.artist', verbose_name='Artist')),
            ],
        ),
    ]
