# Generated by Django 5.1.3 on 2024-11-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_title', models.CharField(max_length=100)),
                ('eng_title', models.CharField(max_length=100)),
                ('jp_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name_roman', models.CharField(max_length=100)),
                ('song_name_jp', models.CharField(max_length=100)),
                ('anime_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.anime')),
                ('artist_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.artist')),
            ],
        ),
    ]
