# Generated by Django 5.1.3 on 2024-11-10 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_rename_default_name_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='eng_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='jp_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='search_engine.anime'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='search_engine.artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name_jp',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_name_roman',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_type',
            field=models.CharField(choices=[('O', 'Opening'), ('E', 'Ending'), ('I', 'Insert')], db_index=True, max_length=10),
        ),
    ]
